"""column published_at in News

Revision ID: 6c1052c6a5cd
Revises: bfa3987c189e
Create Date: 2026-04-17 12:50:26.946059

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6c1052c6a5cd'
down_revision: Union[str, Sequence[str], None] = 'bfa3987c189e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('news', sa.Column('published_at', sa.DateTime(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('news', 'published_at')
    # ### end Alembic commands ###
